pipeline:
  identifier: Build_cicd_pipeline_train_schedule_jenkins_1683571918870
  name: Build cicd-pipeline-train-schedule-jenkins
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1683571864284
        repoName: santhoshreddykeesara/cicd-pipeline-train-schedule-jenkins
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
